apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gaia-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
              readOnly: true
            - mountPath: /var/www/vhost
              name: vhosts
              readOnly: true
        - env:
            - name: WATCH_NGINX_CONF_PATH
              value: /etc/nginx/conf.d
          image: registry.cn-hangzhou.aliyuncs.com/rookieops/nginx-reloader:v1
          imagePullPolicy: IfNotPresent
          name: nginx-reloader
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
              readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        frontend: testfrontend
      restartPolicy: Always
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config
        - hostPath:
            path: /var/www/hyperos/frontend/
            type: Directory
          name: vhosts