apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: gaia-frontend
spec:
  selector:
    app: nginx
  ports:
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 31111
      protocol: TCP
  type: NodePort