apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendpkgmanage
  namespace: fontendpkgmanage
spec:
  selector:
    matchLabels:
      app: frontendpkgmanage
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: frontendpkgmanage
    spec:
      containers:
      - name: hpa
        image: 172.17.9.231:8880/gaia/frontendpkgmanage:v2.4
        ports:
          - containerPort: 8000
