apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: gaia-frontend
spec:
  clusterIP: 10.104.79.45
  clusterIPs:
    - 10.104.79.45
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: frontend
      nodePort: 31111
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort