apiVersion: frontend.pml.com.cn/v1
kind: Vhost
metadata:
  labels:
    app.kubernetes.io/name: vhost
    app.kubernetes.io/instance: vhost-sample
    app.kubernetes.io/part-of: vhost
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vhost
  name: vhost-sample
spec:
  pkgName: test
  domainName: "test.foolishtoohungey.com"